name: Check generated markdown

on:
 pull_request:
   types: 
     - opened
     - synchronize
   paths:
     - 'olddocs/**'

jobs:
 check-generated-markdown:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
     - name: Install dependencies
       run: |
         cd olddocs/gen_edot_col_components
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Check Markdown Generation
       run: |
         cd olddocs
         make check-md-gen
