name: check-links

on:
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  check-links:
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.docs_changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4 # v1.207.0
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
          cache-version: 0
      - name: Install Dependencies
        run: |
          cd docs
          make install
      - name: Check Links
        run: |
          cd docs
          make check-links

  # This job detects if any files changed in a given path
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
  
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
  
      - name: Set output
        run: echo "docs_changed=${{ steps.filter.outputs.docs }}" >> $GITHUB_OUTPUT
